### ISSUE TITLE
The readme doesn't explain how to choose a tagger model when running the postagger server

### ISSUE THREAD

**Issue by ndvbd** [stanfordnlp/python-stanford-corenlp#10]
The readme doesn't explain how to choose a tagger model when running the postagger server

**Comment by arunchaganty** [comment]
If you want to use a non-default tagger model, you'll need to set the appropriate properties flag. For example:
```
properties = {"pos.model": "/path/to/model/"}
with corenlp.CoreNLPClient(annotators="tokenize ssplit pos".split(), properties=properties) as client:
      client.annotate("This is a test sentence.")
```

**Comment by ndvbd** [comment]
@arunchaganty , 
1. Tou supplied the path to the model, but you didn't specify the file names. How do I specify the .tagger filename? How do I specify the .props filename?

2. I am running the server from the command line using:

`java -Xmx500m -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -annotators tokenize,ssplit,pos -port 9001 -timeout 15000`

So I need to create a .properies file and put inside a line with pos.model=/path/to/model/ ?

3. I downloaded a ~1GB English language model from [here](https://stanfordnlp.github.io/CoreNLP/download.html), but I don't see inside the englishPCFG model. How do I find this model?

4. I would like to run the same tagger model as [here](http://nlp.stanford.edu:8080/parser/index.jsp), which is PCFG.

5. When you run the server directly from python, like you did with with corenlp.CoreNLPClient, how do you specify the filename of the JAR?

Thanks.

**Comment by arunchaganty** [comment]
My understanding of what you want (given (4)) is that you actually want to run the constituency parser and use the POS tags it predicts. You can do this by adding `parse` into the list of annotators (so `corenlp.CoreNLPClient(annotators="tokenize ssplit parse".split()` would be sufficient). The documentation at https://stanfordnlp.github.io/CoreNLP/parse.html has more details.

There is a separate concern regarding how to set these properties. There are two possible ways you can invoke the CoreNLPServer:
* Firstly, you can run it as a java command as you mentioned, but in that case you need to specify the properties in when sending a `POST` request to the server. This is completely independent of the python package. See https://stanfordnlp.github.io/CoreNLP/corenlp-server.html for details.
* Secondly, you can call the server directly through this Python package. The location of the CoreNLP package is specified through the `$CORENLP_HOME` environment variable, which you must set, e.g. `export CORENLP_HOME=~/stanford-corenlp-full-2017-06-09/`.

**Comment by ndvbd** [comment]
@arunchaganty, if I use the parse option, then I need to get the tree back, iterate it, and extract the POS tag out of it? That's what they actually did in the online demo page?

So, what you are saying, is that effectively, the result of using the pos annotator are different than the result of using the full parser, and then taking the POS tags out of the leaves. Am I right?

In addition: when I use the parse annotator, the pos.model (the tagger) is not taken into account?

When I enter: "The boy drive well." (mistake on purpose) to the demo page of Stanford, I get:
`The/DT boy/NN drive/VBP well/RB ./.`
See that drive is marked as VBP

However, when I run it by using the CoreNLPParser.parse_text, I get:
```
(ROOT
  (FRAG (NP (DT The) (NN boy) (NN drive)) (ADVP (RB well)) (. .)))
```

See that the drive is marked as NN.
My local java server says that it's using:
`Loading parser from serialized file /stanford-english-corenlp-2018-02-27-models/edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.6 sec].`
And:
`Loading POS tagger from /stanford-english-corenlp-2018-02-27-models/edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger 
`
So even when I use the parse, I get different results ;(

By the way, when I do in python the .parse_text , the server says:
`/127.0.0.1:48226] API call w/annotators tokenize,ssplit,pos,lemma,parse`

so you can see it added the pos,lemma before the parse.

However, when I use the non-server jar: stanford-corenlp-3.9.1.jar, I get the good results:
Constituency parse: 
```
(ROOT
  (S
    (NP (DT The) (NN boy))
    (VP (VBP drive)
      (ADVP (RB well)))
    (. .)))
```

So it feels like there is a difference between the server and the non-server jar.. Strange.

**Comment by ndvbd** [comment]
I think I found the thing. If I add` enforceRequirements = false `in the properties file, the CoreNLP server behave like the CoreNLP, and doesn't add the pos.

**Comment by arunchaganty** [comment]
Ah ok, that makes sense!
