### ISSUE TITLE
Some updates to the readme needed.

### ISSUE THREAD

**Issue by legolego** [stanfordnlp/python-stanford-corenlp#12]
Can you please update the readme file?
The lines for:
`print(sentence.text)`
and
`print(token.lemma)`
don't print anything, those properties don't seem to exist.

Also, the indexes in the lines like:
`matches["sentences"][1]....`
need to be changed to a [0] I believe.

**Comment by arunchaganty** [comment]
Ah, sorry, the default annotators should have included "pos ner lemma" -- I've made that change now.
