### ISSUE TITLE
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/tokensregex?pattern=%28%5Bner%3A+PERSON%5D%2B%29+%2Fwrote%2F+%2Fan%3F%2F+%5B%5D%7B0%2C3%7D+%2Fsentence%7Carticle%2F&filter=False

### ISSUE THREAD

**Issue by hexingren** [stanfordnlp/python-stanford-corenlp#14]
I was trying the Annotation Server Usage code in README.rst with v3.9.1 and v3.8.0, it threw the following errors.

"""
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:9000/tokensregex?pattern=%28%5Bner%3A+PERSON%5D%2B%29+%2Fwrote%2F+%2Fan%3F%2F+%5B%5D%7B0%2C3%7D+%2Fsentence%7Carticle%2F&filter=False

AnnotationException: edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
"""
The same HTTPError happened for the Python wrapper in NLTK. Does it have something to do with CoreNLP version?

When I tried another Python wrapper with v3.9.1, everything worked except NER. So I guess the server should be set-up properly. Could you explain the possible reasons for the HTTPError here? Thanks.

**Comment by ttthy** [comment]
This error is caused by missing param `properties` while request.
I also change the request method from `get` to `post` as mentioned [here](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html)

I've created a pull request for this [pull](https://github.com/stanfordnlp/python-stanford-corenlp/pull/15). Hope it would be merged soon.

**Comment by diegoantognini** [comment]
I guess you are using NER as annotator right ? if yes, just add the properties with ner.useSUTime:0

```
corenlp.CoreNLPClient(annotators="tokenize ssplit lemma pos ner depparse".split(), properties={'ner.useSUTime':0})
```

**Comment by arunchaganty** [comment]
Thanks @thytran2512!
@hexingren, has the fix solved the problem?

**Comment by hexingren** [comment]
Thank you guys @thytran2512 @Diego999 @arunchaganty . I didn't further try this wrapper in April but was inspired by this [thread](https://github.com/sina-al/pynlp/issues/12). We should disable `ner.useSUTime`. @Diego999 was correct.
