### ISSUE TITLE
corenlp.client.TimeoutException: Timeout when executing Tregex query

### ISSUE THREAD

**Issue by phosseini** [stanfordnlp/python-stanford-corenlp#19]
I am trying to use the Tregex for pattern matching and I get the following error:

`corenlp.client.TimeoutException: Timeout when executing Tregex query`

I have no problem using the annotator and the pipeline but I do not know why I am getting the Timeout exception when I am trying to use Tregex. I read something [here](https://github.com/stanfordnlp/python-stanford-corenlp/issues/2) about checking if the server is alive or to cold start the server but I do not know what exactly to do. Any help would be appreciated.

And, just in case you may want to know, my input text is too short: "He had to leave early because he was feeling bad." Even the same example which is provided in test_client.py does not work while the pipeline itself works pretty well. I also tried some of the other suggested solutions (like increasing the timeout time in client class) but non of them works.

**Comment by xzegga** [comment]
Do you resolve this problem? I am getting the same error using TRegex in CoreNLP python wrapper.

**Comment by phosseini** [comment]
@xzegga Not yet! For now, I ended up parsing the raw text of the parser output and coming up with some regular expressions.

**Comment by legolego** [comment]
I have the same issue with CoreNLP 3.91, but no problem with 3.8. My issue is with Semgrex.
I'm running either 3.8/3.91 as a local server with Java 10

`java  --add-modules java.se.ee -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 60000
`

Referenced in python with:

> corenlpProps = {}
corenlpProps["inputFormat"] = "text"
corenlpProps["outputFormat"] = "json"
corenlpProps["serializer"] = "edu.stanford.nlp.pipeline.ProtobufAnnotationSerializer"
corenlpProps["tokenize.options"] = "ptb3Escaping=false,invertible=true"
corenlpProps["timeout"] = "60000"
client = corenlp.CoreNLPClient(start_server=False, endpoint="http://localhost:9000", annotators="tokenize ssplit".split(),
                           properties=corenlpProps)


and I tried .ensure_alive() before running Semgrex:
`client.ensure_alive()`
`
output = client.semgrex(fragment,
                             pattern=SemgrexRule,
                             filter=False)
`

but still get the timeout right away with 3.91:

`File "C:\gitProjects\momo\venv\lib\site-packages\corenlp\client.py", line 244, in __regex
    raise TimeoutException(r.text)
corenlp.client.TimeoutException: Timeout when executing Semgrex query`

**Comment by arunchaganty** [comment]
So, it seems like the root of this issue is that the StanfordCoreNLPServer needs the annotation to be part of its cache before running any of the pattern matchers: in other words, one has to call `annotate(x)` before running tokensregex or tregex. I've made the server automatically do this. If you check `test_client.py`, you'll see a working example of how to call `tokensregex()` and `semgrex()`. A similar call to `tregex()` should also work.
