### ISSUE TITLE
Support for tokensregex/semgrex/tregex

### ISSUE THREAD

**Issue by dan-zheng** [stanfordnlp/python-stanford-corenlp#2]
This CoreNLP interface is great for annotation but doesn't support tokensregex/semgrex/tregex like some non-official interfaces. Could support for tokensregex/semgrex/tregex be added?

**Comment by dan-zheng** [comment]
I made a PR addressing this issue: #4 

My implementation is simple: the `CoreNLPClient` object has new methods (`tokensregex()`, `semgrex()`, `tregex()`) which simply make POST requests to the regex-related endpoints exposed by the CoreNLP server and return the results as dicts.

I wonder if the code is up to par and I'm certainly open to suggestions/edits. One note is that the new regex methods do not fit in with the style of `CoreNLPClient.annotate()` as they do not return protobuf objects. Attributes are accessed dict-style with string keys instead of direct dot notation (`match['sentences']` vs `match.sentences`).

**Comment by vzhong** [comment]
@arunchaganty what do you think?

**Comment by yuhaozhang** [comment]
I think these are very useful enhancements. The added functions can serve as low-level APIs. Beyond that, I think we can also implement a few Annotator, such as `TokensRegexAnnotator`, so that people can easily integrate these by specifying the annotator list.

**Comment by vzhong** [comment]
@yuhaozhang @dan-zheng also made a PR #4 . Can you take a look at that and merge it if you think it's sufficient?

**Comment by vzhong** [comment]
merged. thanks @dan-zheng !

**Comment by arunchaganty** [comment]
Ok, I've merged in this feature. A couple of comments when integrating: it's important to check that the server is alive (calling `ensure_alive`) and turns out that you need to cold start the server to prevent tokensregex/semgrex from timing out. Anyways, thanks for the commit!
