### ISSUE TITLE
Is there a method to get the constituents separately after parsing?

### ISSUE THREAD

**Issue by phosseini** [stanfordnlp/python-stanford-corenlp#23]
This is a question: I am wondering if there is any method to give us the constituents of parsing separately. For example, when I do constituency parsing, the binarized tree is like the following for a sample sentence:
`child {
  child {
    child {
      child {
        value: "I"
      }
      value: "PRP"
    }
    value: "NP"
  }
  child {
    child {
      child {
        child {
          child {
            value: "bought"
          }
          value: "VBD"
        }
        child {
          child {
            child {
              value: "it"
            }
            value: "PRP"
          }
          value: "NP"
        }
        value: "@VP"
      }
      child {
        child {
          child {
            value: "because"
          }
          value: "IN"
        }
        child {
          child {
            child {
              child {
                value: "I"
              }
              value: "PRP"
            }
            value: "NP"
          }
          child {
            child {
              child {
                value: "read"
              }
              value: "VBP"
            }
            child {
              child {
                child {
                  value: "a"
                }
                value: "DT"
              }
              child {
                child {
                  child {
                    value: "good"
                  }
                  value: "JJ"
                }
                child {
                  child {
                    value: "review"
                  }
                  value: "NN"
                }
                value: "@NP"
              }
              value: "NP"
            }
            value: "VP"
          }
          value: "S"
        }
        value: "SBAR"
      }
      value: "VP"
    }
    child {
      child {
        value: "."
      }
      value: "."
    }
    value: "@S"
  }
  value: "S"
}
value: "ROOT"
`
Is there any way/method that I can get for example the NPs, VPs, or Ss separately in a list with their corresponding start/end indexes?

**Comment by arunchaganty** [comment]
Ah, there is nothing in this package to help you with that yet: you'll have to write your own code to do this.

I'd be happy to accept a merge request to include it into the package though!

**Comment by phosseini** [comment]
@arunchaganty I have written a recursive method that returns a list of all the constituents/chunks in the tree based on the output of constituency parser-- would be happy to share my code. However, one problem is that items on this list may have overlaps. It is because when I parse the tree, there's obviously a chance that we have multiple labels of the same type (e.g. VPs or NPs) on the same path to a child. For example, for the input sentence "`I bought the book because I read good reviews about it.`" the list of chunks would be like the following (this is the output of my method and in this case I only listed VPs, NPs, and SBARs):

```
<class 'list'>: 
[['NP', 'I'], 
['NP', 'the book'], 
['NP', 'I'], 
['NP', 'good reviews'],
['NP', 'it'], 
['SBAR', 'because I read good reviews about it'], 
['VP', 'bought the book because I read good reviews about it'], 
['VP', 'read good reviews about it']]
```

As you see, there's an overlap between two of the VPs and the SBAR. Now, my question/confusion is that, how should I handle the overlaps between chunks? Does it depend on where I want to use these chunks? Is there a unique strategy/rule I should follow to resolve the overlaps?
