### ISSUE TITLE
Setting properties in CoreNLPClient.annotate()

### ISSUE THREAD

**Issue by programma256** [stanfordnlp/python-stanford-corenlp#24]
The logic appears to be incorrect when the properties argument is not None in the annotate() call. It looks like [this line](https://github.com/stanfordnlp/python-stanford-corenlp/blob/626009d1bb917b5a1fb66c04776d57c75865f435/corenlp/client.py#L203) should be outdented. Workaround is to set properties when instantiating CoreNLPClient instead.

**Comment by arunchaganty** [comment]
Ah the current logic is that when you specify properties as an argument to `annotate`, it is used instead of the default properties as opposed to being merged / updated from the default properties.
