### ISSUE TITLE
Push latest version to PyPi

### ISSUE THREAD

**Issue by brandomr** [stanfordnlp/python-stanford-corenlp#27]
Is it possible to push the latest version (3.9.2) to PyPi (which is on 3.8.0)? That would be helpful for installing it as a dependency to other packages. Thanks!

**Comment by J38** [comment]
We're actually rebranding all of this as a new software package and deprecating this project in the near future...more info soon!!

**Comment by brandomr** [comment]
Awesome, keep me posted if you can. Anywhere I should be checking for updates?

**Comment by arunchaganty** [comment]
@brandomr And as we wait for the new official incarnation of the python corenlp bindings, I've fixed a few bugs and pushed the new 3.9.2 release to pypi!

**Comment by brandomr** [comment]
That's awesome, thanks @arunchaganty! 👍
