### ISSUE TITLE
Enhanced++ Dependencies

### ISSUE THREAD

**Issue by valeryweber** [stanfordnlp/python-stanford-corenlp#32]
Dear All

I would like to access the

Enhanced++ Dependencies

via the python interface. How can I get this dependency?

Many thanks
valery

**Comment by arunchaganty** [comment]
Again, `stanfordnlp` is probably the package you want to be using, but if you use the `depparse` annotator, the Enhanced++ dependencies are present in the proto returned from the CoreNLP server, but are called `collapsedCCProcessedDependencies`. See https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/CoreNLP.proto for more.
