### ISSUE TITLE
Not possible to modify ParseTree

### ISSUE THREAD

**Issue by lcswillems** [stanfordnlp/python-stanford-corenlp#37]
Hi,
I would like to modify the ParseTree leaves but I can't... I can't add an attribute to a leaf or change its value to a dictionnary. How could I do?

**Comment by AngledLuffa** [comment]
stanza now has a python constituency parser which is more accurate and would allow for rearranging the parse trees.  You can also use stanza's corenlp client to get a tree object and manipulate that if you like.
