### ISSUE TITLE
fail to import stanfordcorenlp

### ISSUE THREAD

**Issue by Mercurium-9** [stanfordnlp/python-stanford-corenlp#40]
I downloaded and set up the stanford core nlp and stanza in anaconda according to the instruction provided on [https://stanfordnlp.github.io/stanza/client_setup.html](url) but I can't import stanfordcorenlp, with it saying 
AssertionError: Please install CoreNLP by running `stanza.install_corenlp()`. If you have installed it, please define $CORENLP_HOME to be location of your CoreNLP distribution or pass in a classpath parameter.
Please help!

**Comment by AngledLuffa** [comment]
What happens if you try to install corenlp or set the CORENLP_HOME variable?

Also, please file any possible issues at

https://github.com/stanfordnlp/stanza

this is super deprecated at this point

**Comment by Mercurium-9** [comment]
ok, thanks!
