### ISSUE TITLE
corenlp has no attribute CoreNLPClient after doing a pip install

### ISSUE THREAD

**Issue by demongolem-biz** [stanfordnlp/python-stanford-corenlp#43]
The error I get is:

> AttributeError: module 'corenlp' has no attribute 'CoreNLPClient'

after doing

`pip install stanford-corenlp`

which installs 3.9.2.

Am I using something which is too old or too new?  Would there be an equivalent thing in Stanza?   I am trying to work with existing code and not writing my own.  I could certainly replace a CoreNLPClient object if there is a better way to do it.

**Comment by AngledLuffa** [comment]
Yes, stanza has a newer version of the client and can take the place of
this library.
